apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hpa-example01
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/codefresh-contrib/gitops-cert-level-2-examples.git
    targetRevision: HEAD
    path: ./custom-diff/01-with-hpa
   
  destination:
    server: https://kubernetes.default.svc
    namespace: example01

  syncPolicy:
    syncOptions:
      - CreateNamespace=true 
    ignoreDifferences:
      - group: apps  # Correct API group for Deployments
        kind: Deployment
        jsonPointers:
          - /spec/replicas  # Ensure ArgoCD ignores this field
      - group: autoscaling  # Ensure HPA changes do not trigger sync issues
        kind: HorizontalPodAutoscaler
        jsonPointers:
          - /spec/replicas
